Always create a new Pause in ThreadFront.instantiatePause()
replayio/devtools pull request #7698
Opened 2022-09-08 14:14 UTC by hbenl

Currently we try to not create multiple pauses for the same point, but I realized that this is unsafe if we receive a pauseId from the backend for a console message or a logpoint result: The message or logpoint result may contain objectIds from that pause, but there can be no guarantee that an objectId will reference the same object in a different pause for the same point.
This also fixes FE-679, where not creating a new pause for a console message also means that the sourceIds in its frames are not updated to the first corresponding sourceId.

2022-09-08 14:45 UTC, markerikson commented
This may be worth discussing further with Brian, specifically since we _are_ trying to avoid having multiple Pause instances per execution point.

2022-09-08 14:54 UTC, bvaughn commented
> Currently we try to not create multiple pauses for the same point, but I realized that this is unsafe if we receive a pauseId from the backend for a console message or a logpoint result: The message or logpoint result may contain objectIds from that pause, but **there can be no guarantee that an objectId will reference the same object in a different pause for the same point.**

This is exactly why we try to avoid creating more than one Pause per point.

Seems like this PR would invalidate _most_ of the frontend object preview caching?

2022-09-08 14:54 UTC, bvaughn requested changes
Preferably, let's _not_ do this, at least not without talking more.

2022-09-08 15:55 UTC, bvaughn commented
> > This is exactly why we try to avoid creating more than one Pause per point.
>
> Huh? But the way it works now means that we may get an objectId from a logpoint result and then try to fetch the object preview using a different pause that was created earlier for the same point - and that may give us the preview of a different object.

We should fix _that_ though, shouldn't we? (We shouldn't ask for the preview data _at a new pause_.)

> > Seems like this PR would invalidate most of the frontend object preview caching?
>
> It would mean that we'll have to cache object previews once for each pause, even if the pauses are for the same point. But I don't see how we can avoid that.

The point is that we're _pre-caching_ a lot of data now for a given point+pause pair. We _have_ to cache object previews at the pause+point level (not just the point level) because of the unstable object ids as you mention. So if we change to always creating a new point, we'll _always_ invalidate any data we may have already cached for that point.

2022-09-08 19:01 UTC, markerikson commented
After _much_ discussion, some takeaways:

- This is driven by trying to make sure that `Location`s in frame data point to the correctly-updated source IDs
- we mutate those `Location`s when the frames are received and processed by the `Pause` instance
- but there are apparently times we do end up with multiple `Pause` instances for a given `ExecutionPoint` and we want to make sure the duplicated frame objects also get processed to have correct locations

We need to do more investigation and thinking about this, but that should wait until we've deleted the old console (hopefully Monday?), and can see exactly what code is still remaining.

It's possible that there's few enough spots that _use_ the frame data and locations that we could actually deal with the "corresponding source" lookups at the UI layer instead (ie, <10 places, rather than "hundreds").

2022-09-28 15:38 UTC, hbenl commented
Closing this since we're removing `Pause` anyway.

2022-09-28 15:38 UTC, closed without merging