Address margins for source viewer search
replayio/devtools pull request #9643
Opened 2023-08-27 23:17 UTC by jonbell-lot23

**Description**

I'm improving the balance for our search box. It was originally [filed](https://linear.app/replay/issue/FE-1828/find-bar-should-not-have-a-border-radius) with a suggestion to remove the border radius. But that would cause its own composition issues. Better is to give the component its own space, with consistent margins.

Old on left, new on right:
<img width="1318" alt="image" src="https://github.com/replayio/devtools/assets/9154902/6073db2a-943d-46d7-a4a7-064b564e91e4">

rem vs px note: we frequently default to .25rem increments, which is great. But there are cases like these where we need more precise than that approach offers.

2023-08-28 13:54 UTC, bvaughn requested changes
Regression on dark mode
<img width="433" alt="Screen Shot 2023-08-28 at 9 54 31 AM" src="https://github.com/replayio/devtools/assets/29597/7af22314-9f37-426f-8448-e1b57e9272b0">

2023-08-28 19:03 UTC, jonbell-lot23 commented
> This change causes a regression (background color) on dark mode:
> 
> <img width="852" alt="Screen Shot 2023-08-28 at 9 54 54 AM" src="https://github.com/replayio/devtools/assets/29597/1f1b5329-ba17-4747-9a10-28cb6086ddd2">
> 
> 
> 
> 

Can you provide more details? I didn't touch the background color in this diff.

2023-08-28 19:18 UTC, bvaughn commented
> I didn't touch the background color in this diff.

I know. Adding margin causes things to break, as shown in the screenshot above.

2023-08-29 09:51 UTC, jonbell-lot23 commented
Moving to new branch: https://github.com/replayio/devtools/pull/9649

It contains the background color adjustment Brian mentioned earlier.

2023-08-29 09:51 UTC, closed without merging