Run updateMappedLocation before RDT view source
replayio/devtools pull request #9726
Opened 2023-09-13 14:09 UTC by Mokshit06

The current RDT view source behaviour sometimes doesn't run `updateMappedLocation` to the list of possible locations to mutate them which leads to the following error:
```
utils.ts:69 Uncaught (in promise) Error: location.sourceId should be updated to the first corresponding sourceId: {"preferredLocation":{"line":36,"column":24,"sourceId":"o58-240-df24f5-31ec2e"},"correspondingSources":["o65-26-df24f5-6c77dd","o58-240-df24f5-31ec2e","o77-354-df24f5-fd421c"]}
    at a (utils.ts:69:18)
    at A (sources.ts:268:3)
    at ReactDevTools.tsx:368:22
    at index.js:16:1
    at Object.dispatch (index.ts:458:18)
    at dispatch (<anonymous>:1:54884)
    at viewElementSourceFunction (ReactDevTools.tsx:711:13)
```

This should fix that

2023-09-13 14:20 UTC, jasonLaster commented
Nice. Have a replay of this bug? Would be fun to see it in action

2023-09-13 15:16 UTC, Mokshit06 commented
There you go :) https://app.replay.io/recording/1f86448e-7400-4bbc-aada-ca5769da27b0

2023-09-13 16:39 UTC, hbenl requested changes

2023-09-13 16:39 UTC, hbenl commented on src/ui/components/SecondaryToolbox/ReactDevTools.tsx
> +          updateMappedLocation(sources, componentFunctionPreview.preview.functionLocation);
There are other places where `ObjectPreview.functionLocation` is used and they will run into the same problem. I think `ObjectPreview.functionLocation` should be updated directly in `preCacheObject()`.

2023-09-15 08:18 UTC, closed without merging

2023-09-15 08:18 UTC, Mokshit06 commented
Ah I opened this PR from my forked repo instead of `replayio/devtools` so the authenticated tests aren't passing. I've created another one and closing this one.